# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: ultralytics_yolo
description: >-
  Flutter plugin for Ultralytics YOLO computer vision models. Supports object detection 
  and image classification on Android and iOS with real-time camera inference.
version: 0.1.4
homepage: https://github.com/ultralytics/yolo-flutter-app
repository: https://github.com/ultralytics/yolo-flutter-app
issue_tracker: https://github.com/ultralytics/yolo-flutter-app/issues
documentation: https://docs.ultralytics.com

topics:
  - computer-vision
  - object-detection
  - yolo
  - machine-learning
  - ai
  - flutter-plugin
  - mobile

# screenshots:
#  - description: "Real-time object detection"
#    path: example/screenshots/detection.png
#  - description: "Image classification"
#    path: example/screenshots/classification.png

funding:
  - https://github.com/sponsors/ultralytics

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  coverage: ^1.14.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  very_good_analysis: ^8.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ultralytics.yolo
        pluginClass: YoloPlugin
      ios:
        pluginClass: YoloPlugin
