# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

name: ultralytics_yolo
description: "Flutter plugin for YOLO (You Only Look Once) models, supporting object detection, segmentation, classification, pose estimation and oriented bounding boxes (OBB) on both Android and iOS."
version: 0.1.3
homepage: https://github.com/ultralytics/yolo-flutter-app
repository: https://github.com/ultralytics/yolo-flutter-app
issue_tracker: https://github.com/ultralytics/yolo-flutter-app/issues
documentation: https://github.com/ultralytics/yolo-flutter-app/blob/main/README.md

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  coverage: 1.13.1
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: com.ultralytics.yolo
        pluginClass: YoloPlugin
      ios:
        pluginClass: YoloPlugin