# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Publish package to pub.dev https://pub.dev/packages/ultralytics_yolo

name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches tags like v0.1.9, v1.0.0, etc.
  workflow_dispatch:
    inputs:
      pubdev:
        type: boolean
        description: Publish to pub.dev

jobs:
  build:
    if: github.repository == 'ultralytics/yolo-flutter-app' && (github.actor == 'glenn-jocher' || github.actor == 'asabri97' || github.actor == 'john-rocky' || github.event_name == 'push')
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: dart pub publish --dry-run
      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: .

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: # for GitHub Deployments tab
      name: Release - pub.dev
      url: https://pub.dev/packages/ultralytics_yolo
    permissions:
      id-token: write # for pub.dev trusted publishing
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
          path: .
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          channel: "stable"
          cache: true
      - uses: dart-lang/setup-dart@v1
      - run: dart pub publish --force

  notify:
    needs: publish
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> "${GITHUB_ENV}"
      - name: Notify Success
        if: needs.publish.result == 'success'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_HUB }}
          payload: |
            text: "<!channel> GitHub Actions success for ${{ github.workflow }} ✅\n\n\n*Repository:* https://github.com/${{ github.repository }}\n*Action:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Author:* ${{ github.actor }}\n*Event:* NEW `ultralytics_yolo ${{ env.TAG_NAME }}` pub.dev package published 🎉\n*Job Status:* ${{ job.status }}"
      - name: Notify Failure
        if: needs.publish.result != 'success'
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: incoming-webhook
          webhook: ${{ secrets.SLACK_WEBHOOK_URL_HUB }}
          payload: |
            text: "<!channel> GitHub Actions error for ${{ github.workflow }} ❌\n\n\n*Repository:* https://github.com/${{ github.repository }}\n*Action:* https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\n*Author:* ${{ github.actor }}\n*Event:* ${{ github.event_name }}\n*Job Status:* ${{ job.status }}"
