# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Publish package to pub.dev https://pub.dev/packages/ultralytics_yolo on tag changes

name: Publish on tag

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # tag-pattern on pub.dev: 'v{{version}}'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
